# Generated by Django 5.0.1 on 2024-02-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('image', models.URLField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
